# Generated by Django 5.2 on 2025-04-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('Current', 'Current'), ('Savings', 'Savings'), ('Lending', 'Lending'), ('Deposits', 'Deposits'), ('Pensions', 'Pensions'), ('Credit Cards', 'Credit Cards')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date', 'bank_name', 'account_name'],
                'indexes': [models.Index(fields=['date', 'bank_name', 'account_name'], name='tracker_mon_date_aa4310_idx')],
            },
        ),
    ]
