# Generated by Django 5.2 on 2025-04-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('account_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('Current', 'Current'), ('Savings', 'Savings'), ('Credit Card', 'Credit Card'), ('Loan', 'Loan'), ('Pension', 'Pension'), ('Expense', 'Expense'), ('Income', 'Income'), ('Tax', 'Tax')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
