# Generated by Django 5.2 on 2025-04-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyentry',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
    ]
